number_of_questions: 100
output_file: "counterfactual_robustness_evaluation"
random_seed: 42
similarity_threshold: 0.95
dataset_source: "json"
file_path: "../data/en_fact.json"
id_field: "id"
question_field: "query"
answer_field: "answer"
models:
  - name: "qwen3:0.6b"
    generator: "ollama"
    provider: "local"
  - name: "qwen-3-32b"
    generator: "openai_compatible"
    provider: "cerebras"
  - name: "openai/gpt-oss-20b"
    generator: "openai_compatible"
    provider: "groq"
  - name: "openai/gpt-oss-120b"
    generator: "openai_compatible"
    provider: "groq"
  - name: "gemma-3-4b-it"
    generator: "google"
    provider: None
  - name: "gemma-3-27b-it"
    generator: "google"
    provider: None

