number_of_questions: 100
output_file: "negative_rejection_evaluation"
similarity_threshold: 0.6
seed: 42
dataset_source: "huggingface"
dataset_path: "hotpot_qa"
dataset_name: "distractor"
split: "train"
models:
#  - name: "openai/gpt-oss-20b"
#    generator: "openai_compatible"
#    provider: "groq"
#  - name: "openai/gpt-oss-120b"
#    generator: "openai_compatible"
#    provider: "groq"
#  - name: "gemma-3-4b-it"
#    generator: "google"
#    provider: None
  - name: "gemma-3-27b-it"
    generator: "google"
    provider: None
#  - name: "qwen/qwen3-4b:free"
#    generator: "openai_compatible"
#    provider: "openrouter"
#  - name: "qwen-3-32b"
#    generator: "openai_compatible"
#    provider: "cerebras"
