number_of_questions: 150
output_file: "noise_robustness_evaluation"
noise_ratios:
  - 0.8
random_seed: 42
dataset_source: "huggingface"
dataset_path: "hotpot_qa"
dataset_name: "distractor"
split: "train"
models:
  - name: "qwen3:0.6b"
    generator: "ollama"
    provider: "local"
  - name: "qwen-3-32b"
    generator: "openai_compatible"
    provider: "cerebras"
  - name: "openai/gpt-oss-20b"
    generator: "openai_compatible"
    provider: "groq"
  - name: "openai/gpt-oss-120b"
    generator: "openai_compatible"
    provider: "groq"
  - name: "gemma-3-4b-it"
    generator: "google"
    provider: None
  - name: "gemma-3-27b-it"
    generator: "google"
    provider: None
